# - Try to find NetCDF

# Create NetCDF C Lbirary
find_library(NETCDF_LIBRARY_C NAMES netcdf
  HINTS ENV NETCDF ENV NETCDF_DIR ENV NETCDF_ROOT
  PATH_SUFFIXES lib lib64
)
find_path(NETCDF_INCLUDE_C NAMES netcdf.h
  HINTS ENV NETCDF ENV NETCDF_DIR ENV NETCDF_ROOT
  PATH_SUFFIXES include
)
add_library(NetCDF_C UNKNOWN IMPORTED)
set_target_properties(NetCDF_C PROPERTIES
  IMPORTED_LOCATION "${NETCDF_LIBRARY_C}"
  INTERFACE_INCLUDE_DIRECTORIES "${NETCDF_INCLUDE_C}"
)

# Create NetCDF Fortran Library
find_library(NETCDF_LIBRARY_Fortran NAMES netcdff
  HINTS ENV NETCDF ENV NETCDF_DIR ENV NETCDF_ROOT
  PATH_SUFFIXES lib lib64
)
find_path(NETCDF_INCLUDE_Fortran NAMES netcdf.mod
  HINTS ENV NETCDF ENV NETCDF_DIR ENV NETCDF_ROOT
  PATH_SUFFIXES include
)
add_library(NetCDF_Fortran UNKNOWN IMPORTED)
set_target_properties(NetCDF_Fortran PROPERTIES
  IMPORTED_LOCATION "${NETCDF_LIBRARY_Fortran}"
  INTERFACE_INCLUDE_DIRECTORIES "${NETCDF_INCLUDE_Fortran}"
  INTERFACE_LINK_LIBRARIES NetCDF_C
)

# Create NetCDF Library
add_library(NetCDF UNKNOWN IMPORTED)
set_target_properties(NetCDF PROPERTIES
  IMPORTED_LOCATION "${NETCDF_LIBRARY_Fortran}"
  INTERFACE_LINK_LIBRARIES NetCDF_Fortran
)
